// <auto-generated />
using System;
using Autoskola.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoskola.DAL.Migrations
{
    [DbContext(typeof(AutoskolaDbContext))]
    [Migration("20251225142027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoskola.DAL.Models.Cas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojCasa")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("InstruktorId")
                        .HasColumnType("int");

                    b.Property<int>("TipCasa")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.HasIndex("VoziloId");

                    b.ToTable("Casovi");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Instruktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojLicence")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodineIskustva")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruktori");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Ispit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstruktorId")
                        .HasColumnType("int");

                    b.Property<int>("TipIspita")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetka")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.IspitVozilo", b =>
                {
                    b.Property<int>("IspitId")
                        .HasColumnType("int");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("IspitId", "VoziloId");

                    b.HasIndex("VoziloId");

                    b.ToTable("IspitVozila");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Kandidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kandidati");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.KandidatCas", b =>
                {
                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.Property<int>("CasId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prisustvovao")
                        .HasColumnType("bit");

                    b.HasKey("KandidatId", "CasId");

                    b.HasIndex("CasId");

                    b.ToTable("KandidatCasovi");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.KandidatIspit", b =>
                {
                    b.Property<int>("KandidatId")
                        .HasColumnType("int");

                    b.Property<int>("IspitId")
                        .HasColumnType("int");

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Polozio")
                        .HasColumnType("bit");

                    b.HasKey("KandidatId", "IspitId");

                    b.HasIndex("IspitId");

                    b.ToTable("KandidatIspiti");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipGoriva")
                        .HasColumnType("int");

                    b.Property<int>("VoznoStanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Cas", b =>
                {
                    b.HasOne("Autoskola.DAL.Models.Instruktor", "Instruktor")
                        .WithMany("Casovi")
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Autoskola.DAL.Models.Vozilo", "Vozilo")
                        .WithMany("Casovi")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instruktor");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Ispit", b =>
                {
                    b.HasOne("Autoskola.DAL.Models.Instruktor", "Instruktor")
                        .WithMany("Ispiti")
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.IspitVozilo", b =>
                {
                    b.HasOne("Autoskola.DAL.Models.Ispit", "Ispit")
                        .WithMany("IspitVozila")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoskola.DAL.Models.Vozilo", "Vozilo")
                        .WithMany("IspitVozila")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.KandidatCas", b =>
                {
                    b.HasOne("Autoskola.DAL.Models.Cas", "Cas")
                        .WithMany("KandidatCasovi")
                        .HasForeignKey("CasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoskola.DAL.Models.Kandidat", "Kandidat")
                        .WithMany("KandidatCasovi")
                        .HasForeignKey("KandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cas");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.KandidatIspit", b =>
                {
                    b.HasOne("Autoskola.DAL.Models.Ispit", "Ispit")
                        .WithMany("KandidatIspiti")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoskola.DAL.Models.Kandidat", "Kandidat")
                        .WithMany("KandidatIspiti")
                        .HasForeignKey("KandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Cas", b =>
                {
                    b.Navigation("KandidatCasovi");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Instruktor", b =>
                {
                    b.Navigation("Casovi");

                    b.Navigation("Ispiti");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Ispit", b =>
                {
                    b.Navigation("IspitVozila");

                    b.Navigation("KandidatIspiti");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Kandidat", b =>
                {
                    b.Navigation("KandidatCasovi");

                    b.Navigation("KandidatIspiti");
                });

            modelBuilder.Entity("Autoskola.DAL.Models.Vozilo", b =>
                {
                    b.Navigation("Casovi");

                    b.Navigation("IspitVozila");
                });
#pragma warning restore 612, 618
        }
    }
}
